export const SENSOR_REQUEST = 'SENSOR_REQUEST'
export const SENSOR_SUCCESS = 'SENSOR_SUCCESS'
export const SENSOR_FAILURE = 'SENSOR_FAILURE'

export const SENSOR_UPDATE_REQUEST = 'SENSOR_UPDATE_REQUEST'
export const SENSOR_UPDATE_SUCCESS = 'SENSOR_UPDATE_SUCCESS'
export const SENSOR_UPDATE_FAILURE = 'SENSOR_UPDATE_FAILURE'

